### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by KevinBurton** [Cordazar/crest#7]
I try to install and I get the below error(s):

H:\crest>npm install crest -g

> dtrace-provider@0.2.8 install C:\Users\KBurton\AppData\Roaming\npm\node_module
s\crest\node_modules\restify\node_modules\dtrace-provider
> node-gyp rebuild

-
C:\Users\KBurton\AppData\Roaming\npm\node_modules\crest\node_modules\restify\nod
e_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v2.4.2, which is not support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:121:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:211:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\KBurton\AppData\Roaming\npm\node_modules\crest\node_module
s\restify\node_modules\dtrace-provider
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bson@0.1.8 install C:\Users\KBurton\AppData\Roaming\npm\node_modules\crest\nod
e_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\KBurton\AppData\Roaming\npm\node_modules\crest\node_modules\mongodb\nod
e_modules\bson>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node  rebuild )
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "crest" "-g"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! path C:\Users\KBurton\AppData\Roaming\npm\node_modules\crest\bin\server

npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\KBurton\AppDa
ta\Roaming\npm\node_modules\crest\bin\server'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     H:\crest\npm-debug.log

One of the first errors is that the Python version needs to be updated. Is this a dependency?

Kevin

**Comment by Nileshmnit08** [comment]
Hi Kevin,

I am also facing some issues 

see if you can help me 


C:\node_modules>npm install crest

> bson@0.1.8 install C:\node_modules\crest\node_modules\mongodb\node_modules\bso
n
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\node_modules\crest\node_modules\mongodb\node_modules\bson>if not defined npm_
config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )


> dtrace-provider@0.2.8 install C:\node_modules\crest\node_modules\restify\node_
modules\dtrace-provider
> node-gyp rebuild


C:\node_modules\crest\node_modules\restify\node_modules\dtrace-provider>if not d
efined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\n
ode-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\node_modules\crest\node_modules\restify\node_modules\dtrace-prov
ider
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "crest"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\node_modules\crest\bin\server
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\node_modules\crest\
bin\server'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node_modules\npm-debug.log

**Comment by KevinBurton** [comment]
Sorry I wished I could. But, I seem to have a different Python problem. The common thread is Python. It seems very dependent on the Python configuration.

Kevin

**Comment by gaborre** [comment]
Before you execute npm install -g, change in the file package.json:
"server": "./bin/server" to "server": "./bin/crest".

Regards!
