### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by Nileshmnit08** [Cordazar/crest#9]
C:\node_modules\bin\cattle_test>npm install crest -g

> bson@0.1.8 install C:\Users\Mishika\AppData\Roaming\npm\node_modules\crest\nod
e_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Mishika\AppData\Roaming\npm\node_modules\crest\node_modules\mongodb\nod
e_modules\bson>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\Users\Mishika\AppData\Roaming\npm\node_modules\cre
st\node_modules\mongodb\node_modules\bson\build\binding.sln]

> dtrace-provider@0.2.8 install C:\Users\Mishika\AppData\Roaming\npm\node_module
s\crest\node_modules\restify\node_modules\dtrace-provider
> node-gyp rebuild

C:\Users\Mishika\AppData\Roaming\npm\node_modules\crest\node_modules\restify\nod
e_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\Users\Mishika\AppData\Roaming\npm\node_modules\cre
st\node_modules\restify\node_modules\dtrace-provider\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Mishika\AppData\Roaming\npm\node_modules\crest\node_module
s\restify\node_modules\dtrace-provider
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "crest" "-g"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\Mishika\AppData\Roaming\npm\node_modules\crest\bin\server

npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Mishika\AppDa
ta\Roaming\npm\node_modules\crest\bin\server'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node_modules\bin\cattle_test\npm-debug.log

**Comment by gaborre** [comment]
Before you execute npm install -g, change in the file package.json:
"server": "./bin/server" to "server": "./bin/crest".

Regards!
